# Workflow to build and publish the module on TestPyPI
name: publish

# The workflow is launched when a push is done on the main branch
on:
  push:
    branches: [ main ]

# List all the jobs to run
jobs:

  # Publish the module on TestPyPI
  publishing:

    # The job will run on this runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    # The sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out the repository, so the job can access it
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools flake8 nose2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check syntax with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build the package
      run: |
        python setup.py build
        python setup.py install
        
    - name: Test with nose2
      run: |
        nose2 -v

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
