# Workflow to build and launch the unit tests
name: test

# The workflow is launched when a push or a pull request is done on the main or the develop branches
on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

# List all the jobs to run
jobs:

  # Launch the unit tests
  testing:

    # The job will run on this runner
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    # The sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out the repository, so the job can access it
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 nose2 setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check syntax with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build the package
      run: |
        python setup.py build
        python setup.py install

    - name: Test with nose2
      run: |
        nose2 -v
